### ISSUE TITLE
Option `close_sidebar_if_opened` is not respected

### ISSUE THREAD

**Issue by driutheman** [miguelgraz/FocusFileOnSidebar#11] opened 2015-03-18 02:58 UTC
Hey,

Great plugin! I realy enjoy it.

Few days ago plugin was updated and `close_sidebar_if_opened` in user preferences file is not respected anymore.

**Comment by yijia-zhan** [comment] 2015-03-18 17:07
I have the same issue.

**Comment by miguelgraz** [comment] 2015-03-18 17:10
Hello folks!

Thanks for taking the time to give feedback, these last days we fixed a memory leak bug, probably my tests missed the `close_sidebar_if_opened` configuration, I'll fix that asap, sorry.

Will keep you informed here :snowboarder:

**Comment by driutheman** [comment] 2015-03-18 17:33
Great. Thanks

**Comment by jhollingworth** [comment] 2015-03-24 11:52
Any update on this?

**Comment by yijia-zhan** [comment] 2015-03-24 15:04
While waiting for a new build, you can use `PackageResourceViewer` to open up `FocusFileOnSidebar` and modify `FocusFileOnSidebar.py`.

**Comment by reversefold** [comment] 2015-03-24 18:35
Having the same issue. @yijia-zhan do you have a proposed change which will fix the issue?

**Comment by ptim** [comment] 2015-05-08 11:20
keen for a sustainable fix for this - thanks for the workaround @yijia-zhan !
(loving the package, tx!)

**Comment by srigi** [comment] 2015-07-04 21:40
Please release a fix otherwise this plugin is pointless.

**Comment by cazacugmihai** [comment] 2015-07-05 18:50
+1 to fix this

**Comment by miguelgraz** [comment] 2015-07-20 00:15
Sorry for taking ages to address this issue, seriously, my bad.
It was caused by my lack of experience with Python, it was modifying a local variable instead of the global one.

So this issue should be fixed now, I'll close this but please take a minute to test it on your computers and report any problem, being this one or another :)

Thank you very much for taking the time to report this error and for your patience, I really appreciate it!

:snowboarder:

**Closed by miguelgraz** 2015-07-20 00:15 UTC
